### ISSUE TITLE
私信作者

### ISSUE THREAD

**Issue by wq624915051** [npuNancy/CarbonInfoSystem#20]
hello，您好，请问您这个项目是用来做什么的呢？ 我看着和我研究的类似，但是有点看不懂具体是用来做什么呢？

**Comment by npuNancy** [comment]
分析pdf，计算各关键词的得分

**Comment by wq624915051** [comment]
hello，您好，因为我目前毕业论文在搞这块，建立碳信息披露框架指标体系，可以加你微信咨询一下吗？

**Comment by wq624915051** [comment]
我看着你建立了一个完整的碳披露指标体系，我也是根据内容分析法建立了一个指标体系，但是我目前在人工阅读打分。。。，感觉有点太慢，不太现实，，，就想着可以通过代码实现一下。。
